---
# vim: filetype=ansible.yaml
# NON-SINGLETON cluster - 2nd and after HA control plane nodes.

# The singleton is any already running k3s controlplane node.  Mostly we
# just need to have the correct node token to use on any other control
# plane or agent node, because we initialize everything on the first
# one and then all other control plane nodes will join on the running
# node for the initial setup.
#
# Otherwise they won't be able to communicate and you'd have three
# isolated control planes, not a single HA control plane.

- name: Ensure prereqs are correct
  ansible.builtin.import_role:
    name: prereqs
  become: true

- name: Copy Jinja template
  ansible.builtin.template:
    src: "config.yaml.j2"
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: '0600'

- name: Copy K3s service file
  ansible.builtin.template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: '0644'

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true
