---
# vim: filetype=ansible.yaml
- name: Import helm subrole
  ansible.builtin.import_tasks: helm.yaml
  become: true

- name: Install HAProxy Operator
  kubernetes.core.helm:
    name: haproxy-operator
    chart_ref: haproxy-operator
    chart_repo_url: https://six-group.github.io/haproxy-operator
    chart_version: "{{ controlplane_haproxy_chart_version }}"
    namespace: haproxy
    create_namespace: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    # use values from var or {}
    values: "{{ controlplane_haproxy_values }}"
    state: present
    wait: true
    wait_timeout: "5m"
  register: controlplane_haproxy_operator_helm
  until: controlplane_haproxy_operator_helm is succeeded
  retries: 3
  delay: 10
