---
# vim: filetype=ansible.yaml
- name: Import helm subrole
  ansible.builtin.import_tasks: helm.yaml
  become: true

- name: Install kube-vip with helm
  kubernetes.core.helm:
    name: argo-cd
    chart_ref: kube-vip
    chart_repo_url: https://kube-vip.github.io/helm-charts
    namespace: argocd
    create_namespace: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    # use values from var or {}
    values: "{{ controlplane_kubevip_values }}"
    state: present
    wait: true
    wait_timeout: "5m"
    chart_version: "{{ controlplane_kubevip_chart_version }}"
  register: controlplane_kubevip_helm
  until: controlplane_kubevip_helm is succeeded
  retries: 3
  delay: 10
