---
apiVersion: v1
kind: Namespace
metadata:
  name: test-nginx
  labels:
    name: test-nginx
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: test-nginx
spec:
  ports:
    - port: 6443
      protocol: TCP
      targetPort: 6443
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: proxy-service
  namespace: test-nginx
  labels:
    # Must be present for EndpointSlice and equal to Service name for automatic
    # mapping - with having it in place, you can change the name of
    # EndpointSlice to something else. The official convention is using Service
    # name as the prefix.
    kubernetes.io/service-name: proxy-service
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 6443
endpoints:
  - addresses:
      - "100.87.28.111"
  - addresses:
      - "100.121.227.115"
  - addresses:
      - "100.83.153.44"
